
-- Drop database if exists (for clean re-run)
IF EXISTS (SELECT name FROM sys.databases WHERE name = 'COMRADES_MARATHON')
BEGIN
    ALTER DATABASE COMRADES_MARATHON SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE COMRADES_MARATHON;
END

-- Create database
CREATE DATABASE COMRADES_MARATHON;




IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='USER_DETAILS' AND xtype='U')
BEGIN
    CREATE TABLE USER_DETAILS (
        USERID INT IDENTITY(1,1) PRIMARY KEY,
        USER_FULLNAME VARCHAR(100) NOT NULL,
        USER_EMAIL VARCHAR(100) NOT NULL UNIQUE,
        PASSWORD_HASH VARCHAR(255) NOT NULL,
        USER_ROLE VARCHAR(50) NOT NULL CHECK (USER_ROLE IN ('Admin', 'Organiser', 'Participant')),
        PHONENUMBER VARCHAR(20) NOT NULL,
        DATE_REGISTERED DATETIME DEFAULT GETDATE(),
        IS_ACTIVE BIT DEFAULT 1
    );
END


IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='EVENTS' AND xtype='U')
BEGIN
    CREATE TABLE EVENTS (
        EVENTID INT IDENTITY(1,1) PRIMARY KEY,
        USERID INT NOT NULL,
        EVENT_NAME VARCHAR(100) NOT NULL,
        DESCRIPTION VARCHAR(500) NOT NULL,
        LOCATION VARCHAR(150) NOT NULL,
        EVENT_DATE DATE NOT NULL,
        EVENT_TIME TIME NOT NULL,
        MAX_PARTICIPANTS INT,
        REGISTRATION_DEADLINE DATE,
        STATUS VARCHAR(20) DEFAULT 'Open' CHECK (STATUS IN ('Draft', 'Open', 'Closed', 'Completed', 'Cancelled')),
        CREATED_AT DATETIME DEFAULT GETDATE(),
        UPDATED_AT DATETIME DEFAULT GETDATE()
    );
    
    ALTER TABLE EVENTS ADD CONSTRAINT FK_EVENTS_USER_DETAILS 
        FOREIGN KEY (USERID) REFERENCES USER_DETAILS(USERID);
END


IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='CATEGORIES' AND xtype='U')
BEGIN
    CREATE TABLE CATEGORIES (
        CATEGORYID INT IDENTITY(1,1) PRIMARY KEY,
        EVENTID INT NOT NULL,
        CATEGORY_NAME VARCHAR(100) NOT NULL,
        DISTANCE DECIMAL(8,2) NOT NULL,
        DISTANCE_UNIT VARCHAR(10) DEFAULT 'km',
        ENTRY_FEE DECIMAL(10,2) NOT NULL DEFAULT 0.00,
        AGE_GROUP_MIN INT,
        AGE_GROUP_MAX INT,
        GENDER_CATEGORY VARCHAR(10) CHECK (GENDER_CATEGORY IN ('Men', 'Women', 'Mixed', 'Open')),
        MAX_PARTICIPANTS INT,
        START_TIME TIME,
        CREATED_AT DATETIME DEFAULT GETDATE(),
        UPDATED_AT DATETIME DEFAULT GETDATE()
    );
    
    ALTER TABLE CATEGORIES ADD CONSTRAINT FK_CATEGORIES_EVENTS 
        FOREIGN KEY (EVENTID) REFERENCES EVENTS(EVENTID);
END


IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='ENROLMENT' AND xtype='U')
BEGIN
    CREATE TABLE ENROLMENT (
        ENROLMENTID INT IDENTITY(1,1) PRIMARY KEY,
        USERID INT NOT NULL,
        EVENTID INT NOT NULL,
        CATEGORYID INT NOT NULL,
        ENROLMENT_DATE DATETIME DEFAULT GETDATE(),
        STATUS VARCHAR(50) NOT NULL DEFAULT 'Pending' 
            CHECK (STATUS IN ('Pending', 'Confirmed', 'Cancelled', 'Completed', 'DNS')),
        BIB_NUMBER VARCHAR(20),
        PAYMENT_STATUS VARCHAR(20) DEFAULT 'Pending' 
            CHECK (PAYMENT_STATUS IN ('Pending', 'Paid', 'Refunded')),
        PAYMENT_AMOUNT DECIMAL(10,2),
        NOTES VARCHAR(255),
        CREATED_AT DATETIME DEFAULT GETDATE(),
        UPDATED_AT DATETIME DEFAULT GETDATE()
    );
    
    ALTER TABLE ENROLMENT ADD CONSTRAINT FK_ENROLMENT_USER_DETAILS 
        FOREIGN KEY (USERID) REFERENCES USER_DETAILS(USERID);
    
    ALTER TABLE ENROLMENT ADD CONSTRAINT FK_ENROLMENT_EVENTS 
        FOREIGN KEY (EVENTID) REFERENCES EVENTS(EVENTID);
    
    ALTER TABLE ENROLMENT ADD CONSTRAINT FK_ENROLMENT_CATEGORIES 
        FOREIGN KEY (CATEGORYID) REFERENCES CATEGORIES(CATEGORYID);
    
    ALTER TABLE ENROLMENT ADD CONSTRAINT UQ_ENROLMENT_USER_EVENT 
        UNIQUE (USERID, EVENTID);
END


IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='RESULTS' AND xtype='U')
BEGIN
    CREATE TABLE RESULTS (
        RESULTID INT IDENTITY(1,1) PRIMARY KEY,
        ENROLMENTID INT NOT NULL,
        FINISH_TIME TIME NOT NULL,
        OVERALL_POSITION INT,
        GENDER_POSITION INT,
        AGE_GROUP_POSITION INT,
        PACE DECIMAL(6,2),
        STATUS VARCHAR(50) NOT NULL DEFAULT 'Pending' 
            CHECK (STATUS IN ('Pending', 'Verified', 'Disqualified')),
        VERIFIED_BY INT,
        VERIFIED_AT DATETIME,
        NOTES VARCHAR(255),
        CREATED_AT DATETIME DEFAULT GETDATE(),
        UPDATED_AT DATETIME DEFAULT GETDATE()
    );
    
    ALTER TABLE RESULTS ADD CONSTRAINT FK_RESULTS_ENROLMENT 
        FOREIGN KEY (ENROLMENTID) REFERENCES ENROLMENT(ENROLMENTID);
    
    ALTER TABLE RESULTS ADD CONSTRAINT FK_RESULTS_VERIFIED_BY 
        FOREIGN KEY (VERIFIED_BY) REFERENCES USER_DETAILS(USERID);
    
    ALTER TABLE RESULTS ADD CONSTRAINT UQ_RESULTS_ENROLMENT 
        UNIQUE (ENROLMENTID);
END


IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='PAYMENTS' AND xtype='U')
BEGIN
    CREATE TABLE PAYMENTS (
        PAYMENTID INT IDENTITY(1,1) PRIMARY KEY,
        ENROLMENTID INT NOT NULL,
        AMOUNT DECIMAL(10,2) NOT NULL,
        PAYMENT_DATE DATETIME DEFAULT GETDATE(),
        PAYMENT_METHOD VARCHAR(50) NOT NULL 
            CHECK (PAYMENT_METHOD IN ('Credit Card', 'Cash', 'Bank Transfer', 'Mobile Money')),
        STATUS VARCHAR(50) NOT NULL DEFAULT 'Pending' 
            CHECK (STATUS IN ('Pending', 'Completed', 'Failed', 'Refunded')),
        TRANSACTION_ID VARCHAR(100),
        NOTES VARCHAR(255),
        CREATED_AT DATETIME DEFAULT GETDATE()
    );
    
    ALTER TABLE PAYMENTS ADD CONSTRAINT FK_PAYMENTS_ENROLMENT 
        FOREIGN KEY (ENROLMENTID) REFERENCES ENROLMENT(ENROLMENTID);
END


IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='ROLES' AND xtype='U')
BEGIN
    CREATE TABLE ROLES (
        ROLEID INT IDENTITY(1,1) PRIMARY KEY,
        ROLE_NAME VARCHAR(50) NOT NULL UNIQUE,
        DESCRIPTION VARCHAR(255),
        CREATED_AT DATETIME DEFAULT GETDATE()
    );
END


-- CREATE INDEXES (for performance)

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name='IX_USER_DETAILS_EMAIL')
    CREATE INDEX IX_USER_DETAILS_EMAIL ON USER_DETAILS(USER_EMAIL);

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name='IX_EVENTS_USERID')
    CREATE INDEX IX_EVENTS_USERID ON EVENTS(USERID);

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name='IX_EVENTS_DATE')
    CREATE INDEX IX_EVENTS_DATE ON EVENTS(EVENT_DATE);

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name='IX_EVENTS_STATUS')
    CREATE INDEX IX_EVENTS_STATUS ON EVENTS(STATUS);

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name='IX_CATEGORIES_EVENTID')
    CREATE INDEX IX_CATEGORIES_EVENTID ON CATEGORIES(EVENTID);

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name='IX_ENROLMENT_USERID')
    CREATE INDEX IX_ENROLMENT_USERID ON ENROLMENT(USERID);

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name='IX_ENROLMENT_EVENTID')
    CREATE INDEX IX_ENROLMENT_EVENTID ON ENROLMENT(EVENTID);

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name='IX_ENROLMENT_STATUS')
    CREATE INDEX IX_ENROLMENT_STATUS ON ENROLMENT(STATUS);

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name='IX_RESULTS_ENROLMENTID')
    CREATE INDEX IX_RESULTS_ENROLMENTID ON RESULTS(ENROLMENTID);

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name='IX_PAYMENTS_ENROLMENTID')
    CREATE INDEX IX_PAYMENTS_ENROLMENTID ON PAYMENTS(ENROLMENTID);


DELETE FROM PAYMENTS;
DELETE FROM RESULTS;
DELETE FROM ENROLMENT;
DELETE FROM CATEGORIES;
DELETE FROM EVENTS;
DELETE FROM USER_DETAILS;
DELETE FROM ROLES;

-- Reset identity columns
DBCC CHECKIDENT ('USER_DETAILS', RESEED, 0);
DBCC CHECKIDENT ('EVENTS', RESEED, 0);
DBCC CHECKIDENT ('CATEGORIES', RESEED, 0);
DBCC CHECKIDENT ('ENROLMENT', RESEED, 0);
DBCC CHECKIDENT ('RESULTS', RESEED, 0);
DBCC CHECKIDENT ('PAYMENTS', RESEED, 0);
DBCC CHECKIDENT ('ROLES', RESEED, 0);



-- Insert sample users
INSERT INTO USER_DETAILS (USER_FULLNAME, USER_EMAIL, PASSWORD_HASH, USER_ROLE, PHONENUMBER) VALUES
    ('John Organiser', 'john@raceday.com', 'HASHED_PASSWORD_123', 'Organiser', '+27721234567'),
    ('Jane Organiser', 'jane@raceday.com', 'HASHED_PASSWORD_456', 'Organiser', '+27729876543'),
    ('Alice Runner', 'alice@email.com', 'HASHED_PASSWORD_789', 'Participant', '+27727890123'),
    ('Bob Runner', 'bob@email.com', 'HASHED_PASSWORD_012', 'Participant', '+27728901234'),
    ('Carol Runner', 'carol@email.com', 'HASHED_PASSWORD_345', 'Participant', '+27729012345'),
    ('Admin User', 'admin@raceday.com', 'HASHED_PASSWORD_ADMIN', 'Admin', '+27720123456');

-- Insert events
INSERT INTO EVENTS (USERID, EVENT_NAME, DESCRIPTION, LOCATION, EVENT_DATE, EVENT_TIME, MAX_PARTICIPANTS, REGISTRATION_DEADLINE, STATUS) VALUES
    (1, 'Cape Town Marathon 2025', 'Annual marathon through scenic Cape Town', 'Cape Town, South Africa', '2025-04-15', '06:00:00', 1000, '2025-04-10', 'Open'),
    (1, 'Park Run Century City', 'Weekly 5km fun run', 'Century City, Cape Town', '2025-03-22', '07:30:00', 300, '2025-03-21', 'Open'),
    (2, 'Durban 10km Challenge', 'Fast 10km race along beachfront', 'Durban, South Africa', '2025-05-10', '06:30:00', 500, '2025-05-05', 'Open'),
    (2, 'Trail Run Table Mountain', 'Challenging trail run', 'Cape Town, South Africa', '2025-06-20', '07:00:00', 150, '2025-06-15', 'Draft');

-- Insert categories
INSERT INTO CATEGORIES (EVENTID, CATEGORY_NAME, DISTANCE, ENTRY_FEE, AGE_GROUP_MIN, AGE_GROUP_MAX, GENDER_CATEGORY, MAX_PARTICIPANTS) VALUES
    (1, 'Full Marathon', 42.20, 250.00, 18, 99, 'Open', 500),
    (1, 'Half Marathon - Men', 21.10, 150.00, 16, 99, 'Men', 300),
    (1, 'Half Marathon - Women', 21.10, 150.00, 16, 99, 'Women', 200),
    (1, '10km Fun Run', 10.00, 50.00, 12, 99, 'Mixed', 200),
    (2, '5km Run', 5.00, 0.00, 10, 99, 'Mixed', 300),
    (2, '5km Walk', 5.00, 0.00, 8, 99, 'Mixed', 100),
    (3, '10km Open', 10.00, 100.00, 15, 99, 'Open', 500),
    (4, '12km Trail', 12.00, 80.00, 12, 99, 'Mixed', 80),
    (4, '21km Trail', 21.00, 120.00, 18, 99, 'Open', 70);

-- Insert enrolments
INSERT INTO ENROLMENT (USERID, EVENTID, CATEGORYID, STATUS, PAYMENT_STATUS, PAYMENT_AMOUNT, BIB_NUMBER) VALUES
    (3, 1, 1, 'Confirmed', 'Paid', 250.00, 'BIB-001'),
    (4, 1, 2, 'Confirmed', 'Paid', 150.00, 'BIB-002'),
    (5, 1, 3, 'Pending', 'Pending', 150.00, NULL),
    (6, 2, 5, 'Confirmed', 'Paid', 0.00, 'BIB-003'),
    (3, 2, 5, 'Confirmed', 'Paid', 0.00, 'BIB-004'),
    (4, 3, 7, 'Pending', 'Pending', 100.00, NULL),
    (5, 3, 7, 'Confirmed', 'Paid', 100.00, 'BIB-005');

-- Insert results
INSERT INTO RESULTS (ENROLMENTID, FINISH_TIME, OVERALL_POSITION, GENDER_POSITION, AGE_GROUP_POSITION, PACE, STATUS, VERIFIED_BY, VERIFIED_AT) VALUES
    (1, '03:45:45', 25, 5, 2, 5.33, 'Verified', 1, GETDATE()),
    (2, '01:25:15', 15, 10, 1, 4.03, 'Verified', 1, GETDATE()),
    (5, '00:22:30', 45, 20, 8, 4.50, 'Verified', 2, GETDATE());

-- Insert payments
INSERT INTO PAYMENTS (ENROLMENTID, AMOUNT, PAYMENT_METHOD, TRANSACTION_ID, STATUS) VALUES
    (1, 250.00, 'Credit Card', 'TXN-001', 'Completed'),
    (2, 150.00, 'Bank Transfer', 'TXN-002', 'Completed'),
    (4, 0.00, 'Cash', 'TXN-003', 'Completed'),
    (5, 0.00, 'Cash', 'TXN-004', 'Completed'),
    (7, 100.00, 'Mobile Money', 'TXN-005', 'Completed');

-- Insert roles
INSERT INTO ROLES (ROLE_NAME, DESCRIPTION) VALUES
    ('Admin', 'Full system access'),
    ('Organiser', 'Can create and manage events'),
    ('Participant', 'Can enrol and view results');


SELECT 'DATABASE CREATED SUCCESSFULLY ' AS Message;

SELECT 'USER_DETAILS' AS TableName, COUNT(*) AS RecordCount FROM USER_DETAILS
UNION ALL SELECT 'EVENTS', COUNT(*) FROM EVENTS
UNION ALL SELECT 'CATEGORIES', COUNT(*) FROM CATEGORIES
UNION ALL SELECT 'ENROLMENT', COUNT(*) FROM ENROLMENT
UNION ALL SELECT 'RESULTS', COUNT(*) FROM RESULTS
UNION ALL SELECT 'PAYMENTS', COUNT(*) FROM PAYMENTS
UNION ALL SELECT 'ROLES', COUNT(*) FROM ROLES
ORDER BY TableName;

-- Show sample data
SELECT 'SAMPLE DATA ' AS Message;

-- Users
SELECT USERID, USER_FULLNAME, USER_EMAIL, USER_ROLE, PHONENUMBER 
FROM USER_DETAILS;

-- Events with Organiser
SELECT e.EVENTID, e.EVENT_NAME, e.EVENT_DATE, e.LOCATION, u.USER_FULLNAME AS ORGANISER
FROM EVENTS e
JOIN USER_DETAILS u ON e.USERID = u.USERID;

-- Enrolments with details
SELECT en.ENROLMENTID, u.USER_FULLNAME AS PARTICIPANT, e.EVENT_NAME, c.CATEGORY_NAME, en.STATUS
FROM ENROLMENT en
JOIN USER_DETAILS u ON en.USERID = u.USERID
JOIN EVENTS e ON en.EVENTID = e.EVENTID
JOIN CATEGORIES c ON en.CATEGORYID = c.CATEGORYID;